spring.data.mongodb.uri=mongodb+srv://aryansuryawanhi1435_db_user:n84zOzhZ14vuJSFW@cluster0.tpldjmg.mongodb.net/mealcircle?retryWrites=true&w=majority
spring.data.mongodb.database=mealcircle

server.port=9090