spring.data.mongodb.uri=mongodb+srv://aryansuryawanhi1435_db_user:n84zOzhZ14vuJSFW@cluster0.tpldjmg.mongodb.net/mealcircle?retryWrites=true&w=majority
spring.data.mongodb.database=mealcircle

server.port=9090

cloudinary.cloud-name=da30huwky
cloudinary.api-key=278571876557545
cloudinary.api-secret=Wdw-7ySgwHyE-Gdg40YPh9Hi_xE

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Razorpay test-mode credentials
razorpay.key-id=rzp_test_SXg8ri9IKdsb9t
razorpay.key-secret=ZN6GR4NtQBQe5LD7C8AGPpgh